export type PriceValue =
  | number
  | string;

export type WatchListItem = {
  id: string;

  brand: string;
  model: string;
  name: string;

  description: string | null;

  /*
   * Stored image information.
   *
   * imageUrl is kept temporarily for
   * backward compatibility.
   *
   * imageUrls contains the stored gallery URLs.
   *
   * imagePublicIds contains the matching
   * Cloudinary public IDs used for image
   * management by the Admin.
   *
   * The arrays are aligned by index:
   *
   * imageUrls[index]
   * imagePublicIds[index]
   *
   * both describe the same image.
   */
  imageUrl: string | null;
  imageUrls: string[];
  imagePublicIds: string[];

  /*
   * Signed delivery URLs generated by
   * the backend.
   *
   * These are the URLs that should be used
   * when rendering authenticated Cloudinary
   * images in the frontend.
   */
  displayImageUrl: string | null;
  displayImageUrls: string[];

  adminCostPrice: PriceValue;
  defaultSupplierPrice: PriceValue;
  recommendedSalePrice: PriceValue;

  isActive: boolean;

  createdAt: string;
  updatedAt: string;

  warehouseInventory:
    | {
        quantityOnHand: number;
      }
    | null;
};

export type WatchDetails = {
  id: string;

  brand: string;
  model: string;
  name: string;

  description: string | null;

  /*
   * Stored image information.
   */
  imageUrl: string | null;
  imageUrls: string[];
  imagePublicIds: string[];

  /*
   * Signed URLs intended only for rendering.
   */
  displayImageUrl: string | null;
  displayImageUrls: string[];

  adminCostPrice: PriceValue;
  defaultSupplierPrice: PriceValue;
  recommendedSalePrice: PriceValue;

  isActive: boolean;

  createdAt: string;
  updatedAt: string;

  warehouseInventory:
    | {
        quantityOnHand: number;
        updatedAt?: string;
      }
    | null;

  _count?: {
    supplierInventories?: number;
    allocations?: number;
    saleItems?: number;
  };
};

export type CreateWatchInput = {
  brand: string;
  model: string;
  name: string;

  description?: string;

  /*
   * imageUrl remains temporarily for
   * backward compatibility.
   *
   * New watch creation should normally send
   * imageUrls together with imagePublicIds.
   */
  imageUrl?: string;

  imageUrls?: string[];
  imagePublicIds?: string[];

  adminCostPrice: number;
  defaultSupplierPrice: number;
  recommendedSalePrice: number;

  initialQuantity: number;
};

export type UpdateWatchInput = {
  brand?: string;
  model?: string;
  name?: string;

  description?: string | null;

  /*
   * imageUrl remains temporarily for
   * backward compatibility.
   *
   * Gallery updates should send imageUrls
   * and imagePublicIds together so both
   * arrays remain synchronized.
   */
  imageUrl?: string | null;

  imageUrls?: string[];
  imagePublicIds?: string[];

  adminCostPrice?: number;
  defaultSupplierPrice?: number;
  recommendedSalePrice?: number;
};