import {
  useEffect,
  useRef,
  useState,
} from "react";

import {
  Alert,
  Box,
  Button,
  Dialog,
  DialogActions,
  DialogContent,
  DialogTitle,
  Stack,
  TextField,
  Typography,
} from "@mui/material";

import {
  HttpError,
} from "../../api/http";

import {
  uploadWatchImages,
} from "../../api/uploads";

import {
  createWatch,
  updateWatch,
} from "../../api/watches";

import type {
  UploadedWatchImage,
} from "../../api/uploads";

import type {
  WatchDetails,
} from "../../types/watch";

type WatchDialogProps = {
  open: boolean;

  watch:
  | WatchDetails
  | null;

  onClose: () => void;

  onSaved: () => void;
};

type ExistingGalleryImage = {
  id: string;

  kind: "existing";

  /*
   * Original URL stored in the database.
   *
   * This value is sent back to the backend
   * when the watch is updated.
   */
  storedUrl: string;

  /*
   * Signed URL generated by the backend.
   *
   * This value is used only for rendering
   * the authenticated Cloudinary image.
   */
  displayUrl: string;

  publicId: string;
};

type NewGalleryImage = {
  id: string;

  kind: "new";

  file: File;

  /*
   * Temporary local browser URL used only
   * for preview before uploading.
   */
  previewUrl: string;
};

type GalleryImage =
  | ExistingGalleryImage
  | NewGalleryImage;

const MAX_WATCH_IMAGES =
  10;

const MAX_IMAGE_SIZE_BYTES =
  10 * 1024 * 1024;

function isValidMoney(
  value: string,
): boolean {
  const number =
    Number(value);

  if (
    !Number.isFinite(number) ||
    number < 0
  ) {
    return false;
  }

  return /^\d+(\.\d{1,2})?$/.test(
    value,
  );
}

function createGalleryId(): string {
  return `${Date.now()}-${Math.random()
    .toString(36)
    .slice(2)}`;
}

function getGalleryImagePreview(
  image: GalleryImage,
): string {
  return image.kind ===
    "existing"
    ? image.displayUrl
    : image.previewUrl;
}

function isSameFile(
  first: File,
  second: File,
): boolean {
  return (
    first.name ===
    second.name &&
    first.size ===
    second.size &&
    first.lastModified ===
    second.lastModified
  );
}

export default function WatchDialog({
  open,
  watch,
  onClose,
  onSaved,
}: WatchDialogProps) {
  const isEdit =
    watch !== null;

  const previewUrlsRef =
    useRef(
      new Set<string>(),
    );

  const [
    brand,
    setBrand,
  ] = useState("");

  const [
    model,
    setModel,
  ] = useState("");

  const [
    name,
    setName,
  ] = useState("");

  const [
    description,
    setDescription,
  ] = useState("");

  const [
    galleryImages,
    setGalleryImages,
  ] = useState<
    GalleryImage[]
  >([]);

  const [
    adminCostPrice,
    setAdminCostPrice,
  ] = useState("");

  const [
    defaultSupplierPrice,
    setDefaultSupplierPrice,
  ] = useState("");

  const [
    recommendedSalePrice,
    setRecommendedSalePrice,
  ] = useState("");

  const [
    initialQuantity,
    setInitialQuantity,
  ] = useState("0");

  const [
    error,
    setError,
  ] = useState("");

  const [
    isSaving,
    setIsSaving,
  ] = useState(false);

  const [
    saveMessage,
    setSaveMessage,
  ] = useState("");

  /*
   * Revokes all temporary browser preview URLs.
   *
   * This prevents local object URLs from staying
   * in memory after the dialog is closed or reset.
   */
  function clearLocalPreviewUrls() {
    previewUrlsRef.current.forEach(
      (previewUrl) => {
        URL.revokeObjectURL(
          previewUrl,
        );
      },
    );

    previewUrlsRef.current.clear();
  }

  /*
   * Cleanup local preview URLs when the
   * component is finally unmounted.
   */
  useEffect(() => {
    return () => {
      previewUrlsRef.current.forEach(
        (previewUrl) => {
          URL.revokeObjectURL(
            previewUrl,
          );
        },
      );

      previewUrlsRef.current.clear();
    };
  }, []);

  /*
   * Initializes the form whenever the
   * dialog opens.
   */
  useEffect(() => {
    if (!open) {
      clearLocalPreviewUrls();

      return;
    }

    /*
     * Remove preview URLs belonging to a
     * previous dialog session.
     */
    clearLocalPreviewUrls();

    setBrand(
      watch?.brand ??
      "",
    );

    setModel(
      watch?.model ??
      "",
    );

    setName(
      watch?.name ??
      "",
    );

    setDescription(
      watch?.description ??
      "",
    );

    /*
     * Build the existing gallery.
     *
     * storedUrls are the original values that
     * must be sent back to the backend.
     *
     * displayUrls are signed URLs used only
     * for showing authenticated Cloudinary
     * images in the browser.
     */
    const storedUrls =
      watch?.imageUrls
        ?.length
        ? watch.imageUrls
        : watch?.imageUrl
          ? [
            watch.imageUrl,
          ]
          : [];

    const displayUrls =
      watch?.displayImageUrls
        ?.length
        ? watch.displayImageUrls
        : watch?.displayImageUrl
          ? [
            watch.displayImageUrl,
          ]
          : storedUrls;

    const publicIds =
      watch?.imagePublicIds ??
      [];

    const existingImages =
      storedUrls.map(
        (
          storedUrl,
          index,
        ): ExistingGalleryImage => ({
          id:
            `existing-${index}-${storedUrl}`,

          kind:
            "existing",

          storedUrl,

          displayUrl:
            displayUrls[
            index
            ] ??
            storedUrl,

          publicId:
            publicIds[
            index
            ] ??
            "",
        }),
      );

    setGalleryImages(
      existingImages,
    );

    setAdminCostPrice(
      watch
        ? String(
          watch.adminCostPrice,
        )
        : "",
    );

    setDefaultSupplierPrice(
      watch
        ? String(
          watch.defaultSupplierPrice,
        )
        : "",
    );

    setRecommendedSalePrice(
      watch
        ? String(
          watch.recommendedSalePrice,
        )
        : "",
    );

    /*
     * Initial quantity is relevant only
     * when creating a new watch.
     */
    setInitialQuantity(
      "0",
    );

    setError("");
    setSaveMessage("");
  }, [
    open,
    watch,
  ]);

  /*
   * Adds files selected from the computer
   * or mobile device to the local gallery.
   *
   * Files are NOT uploaded yet.
   *
   * Upload happens only when the Admin saves
   * the watch, which reduces unnecessary
   * Cloudinary uploads when the dialog is
   * cancelled.
   */
  function handleFilesSelected(
    selectedFiles:
      FileList | null,
  ) {
    if (
      !selectedFiles ||
      selectedFiles.length ===
      0
    ) {
      return;
    }

    const files =
      Array.from(
        selectedFiles,
      );

    if (
      galleryImages.length +
      files.length >
      MAX_WATCH_IMAGES
    ) {
      setError(
        `ניתן להוסיף עד ${MAX_WATCH_IMAGES} תמונות לכל שעון. כרגע יש ${galleryImages.length} תמונות בגלריה.`,
      );

      return;
    }

    const invalidType =
      files.find(
        (file) =>
          !file.type.startsWith(
            "image/",
          ),
      );

    if (invalidType) {
      setError(
        `הקובץ "${invalidType.name}" אינו קובץ תמונה תקין`,
      );

      return;
    }

    const oversizedFile =
      files.find(
        (file) =>
          file.size >
          MAX_IMAGE_SIZE_BYTES,
      );

    if (oversizedFile) {
      setError(
        `התמונה "${oversizedFile.name}" גדולה מ-10MB`,
      );

      return;
    }

    /*
     * Prevent selecting the same new local file
     * more than once in the same gallery.
     */
    const currentNewFiles =
      galleryImages
        .filter(
          (
            image,
          ): image is NewGalleryImage =>
            image.kind ===
            "new",
        )
        .map(
          (image) =>
            image.file,
        );

    const uniqueFiles =
      files.filter(
        (file) =>
          !currentNewFiles.some(
            (
              existingFile,
            ) =>
              isSameFile(
                file,
                existingFile,
              ),
          ),
      );

    if (
      uniqueFiles.length ===
      0
    ) {
      setError(
        "התמונות שנבחרו כבר נמצאות בגלריה",
      );

      return;
    }

    const newImages =
      uniqueFiles.map(
        (
          file,
        ): NewGalleryImage => {
          const previewUrl =
            URL.createObjectURL(
              file,
            );

          previewUrlsRef.current.add(
            previewUrl,
          );

          return {
            id:
              createGalleryId(),

            kind:
              "new",

            file,

            previewUrl,
          };
        },
      );

    setGalleryImages(
      (current) => [
        ...current,
        ...newImages,
      ],
    );

    setError("");
  }

  /*
   * Removes one image from the current gallery.
   *
   * New local images have their temporary
   * object URL revoked immediately.
   *
   * Existing Cloudinary assets are removed from
   * the watch gallery after save. Physical
   * Cloudinary cleanup will be handled separately
   * by the backend cleanup flow.
   */
  function removeGalleryImage(
    index: number,
  ) {
    setGalleryImages(
      (current) => {
        const image =
          current[
          index
          ];

        if (!image) {
          return current;
        }

        if (
          image.kind ===
          "new"
        ) {
          URL.revokeObjectURL(
            image.previewUrl,
          );

          previewUrlsRef.current.delete(
            image.previewUrl,
          );
        }

        return current.filter(
          (
            _image,
            currentIndex,
          ) =>
            currentIndex !==
            index,
        );
      },
    );

    setError("");
  }

  /*
   * Moves an image one position forward
   * or backward in the gallery.
   *
   * Array index 0 is always the primary image.
   */
  function moveGalleryImage(
    index: number,
    direction:
      | -1
      | 1,
  ) {
    setGalleryImages(
      (current) => {
        const targetIndex =
          index +
          direction;

        if (
          targetIndex <
          0 ||
          targetIndex >=
          current.length
        ) {
          return current;
        }

        const next =
          [
            ...current,
          ];

        const [
          movedImage,
        ] =
          next.splice(
            index,
            1,
          );

        if (!movedImage) {
          return current;
        }

        next.splice(
          targetIndex,
          0,
          movedImage,
        );

        return next;
      },
    );
  }

  /*
   * Makes one image the primary watch image
   * by moving it to array index 0.
   */
  function setPrimaryImage(
    index: number,
  ) {
    if (
      index ===
      0
    ) {
      return;
    }

    setGalleryImages(
      (current) => {
        const next =
          [
            ...current,
          ];

        const [
          selectedImage,
        ] =
          next.splice(
            index,
            1,
          );

        if (!selectedImage) {
          return current;
        }

        next.unshift(
          selectedImage,
        );

        return next;
      },
    );
  }

  /*
   * Uploads only new local files and combines
   * the results with existing Cloudinary images
   * while preserving the current gallery order.
   */
  async function buildFinalImageGallery(): Promise<{
    imageUrls: string[];
    imagePublicIds: string[];
  }> {
    const currentGallery =
      [
        ...galleryImages,
      ];

    const newImages =
      currentGallery.filter(
        (
          image,
        ): image is NewGalleryImage =>
          image.kind ===
          "new",
      );

    const uploadedByImageId =
      new Map<
        string,
        UploadedWatchImage
      >();

    if (
      newImages.length >
      0
    ) {
      setSaveMessage(
        newImages.length ===
          1
          ? "מעלה תמונה..."
          : `מעלה ${newImages.length} תמונות...`,
      );

      const uploadedImages =
        await uploadWatchImages(
          newImages.map(
            (image) =>
              image.file,
          ),
        );

      newImages.forEach(
        (
          image,
          index,
        ) => {
          const uploadedImage =
            uploadedImages[
            index
            ];

          if (!uploadedImage) {
            throw new Error(
              "העלאת התמונות לא הושלמה",
            );
          }

          uploadedByImageId.set(
            image.id,
            uploadedImage,
          );
        },
      );
    }

    const imageUrls:
      string[] =
      [];

    const imagePublicIds:
      string[] =
      [];

    for (
      const image of
      currentGallery
    ) {
      if (
        image.kind ===
        "existing"
      ) {
        imageUrls.push(
          image.storedUrl,
        );

        imagePublicIds.push(
          image.publicId,
        );

        continue;
      }

      const uploadedImage =
        uploadedByImageId.get(
          image.id,
        );

      if (!uploadedImage) {
        throw new Error(
          "חסרים נתונים עבור אחת התמונות שהועלו",
        );
      }

      imageUrls.push(
        uploadedImage.url,
      );

      imagePublicIds.push(
        uploadedImage.publicId,
      );
    }

    return {
      imageUrls,
      imagePublicIds,
    };
  }

  async function handleSave() {
    const normalizedBrand =
      brand.trim();

    const normalizedModel =
      model.trim();

    const normalizedName =
      name.trim();

    if (
      !normalizedBrand ||
      !normalizedModel ||
      !normalizedName
    ) {
      setError(
        "יש להזין מותג, דגם ושם שעון",
      );

      return;
    }

    /*
     * Validate all price fields.
     */
    if (
      !isValidMoney(
        adminCostPrice,
      ) ||
      !isValidMoney(
        defaultSupplierPrice,
      ) ||
      !isValidMoney(
        recommendedSalePrice,
      )
    ) {
      setError(
        "יש להזין מחירים תקינים עם עד שתי ספרות אחרי הנקודה",
      );

      return;
    }

    if (
      galleryImages.length >
      MAX_WATCH_IMAGES
    ) {
      setError(
        `ניתן להוסיף עד ${MAX_WATCH_IMAGES} תמונות לכל שעון`,
      );

      return;
    }

    const parsedInitialQuantity =
      Number(
        initialQuantity,
      );

    /*
     * Initial warehouse quantity is relevant
     * only when creating a new watch.
     */
    if (
      !isEdit &&
      (
        !Number.isInteger(
          parsedInitialQuantity,
        ) ||
        parsedInitialQuantity <
        0
      )
    ) {
      setError(
        "המלאי ההתחלתי חייב להיות מספר שלם שאינו שלילי",
      );

      return;
    }

    setError("");
    setIsSaving(true);
    setSaveMessage(
      "שומר...",
    );

    try {
      const {
        imageUrls,
        imagePublicIds,
      } =
        await buildFinalImageGallery();

      setSaveMessage(
        "שומר את פרטי השעון...",
      );

      if (watch) {
        /*
         * Update an existing watch.
         */
        await updateWatch(
          watch.id,
          {
            brand:
              normalizedBrand,

            model:
              normalizedModel,

            name:
              normalizedName,

            description:
              description.trim() ||
              null,

            /*
             * Stored gallery information.
             *
             * Signed display URLs are never sent
             * back to the backend.
             */
            imageUrls,

            imagePublicIds,

            adminCostPrice:
              Number(
                adminCostPrice,
              ),

            defaultSupplierPrice:
              Number(
                defaultSupplierPrice,
              ),

            recommendedSalePrice:
              Number(
                recommendedSalePrice,
              ),
          },
        );
      } else {
        /*
         * Create a new watch.
         */
        await createWatch({
          brand:
            normalizedBrand,

          model:
            normalizedModel,

          name:
            normalizedName,

          description:
            description.trim() ||
            undefined,

          imageUrls,

          imagePublicIds,

          adminCostPrice:
            Number(
              adminCostPrice,
            ),

          defaultSupplierPrice:
            Number(
              defaultSupplierPrice,
            ),

          recommendedSalePrice:
            Number(
              recommendedSalePrice,
            ),

          initialQuantity:
            parsedInitialQuantity,
        });
      }

      onSaved();
      onClose();
    } catch (caughtError) {
      if (
        caughtError instanceof
        HttpError
      ) {
        setError(
          caughtError.message,
        );
      } else if (
        caughtError instanceof
        Error
      ) {
        setError(
          caughtError.message ||
          "לא ניתן לשמור את פרטי השעון",
        );
      } else {
        setError(
          "לא ניתן לשמור את פרטי השעון",
        );
      }
    } finally {
      setIsSaving(false);
      setSaveMessage("");
    }
  }

  return (
    <Dialog
      open={open}
      onClose={
        isSaving
          ? undefined
          : onClose
      }
      fullWidth
      maxWidth="md"
    >
      <DialogTitle>
        {isEdit
          ? "עריכת שעון"
          : "הוספת שעון חדש"}
      </DialogTitle>

      <DialogContent>
        <Stack
          spacing={2.2}
          sx={{
            pt: 1,
          }}
        >
          {error && (
            <Alert
              severity="error"
            >
              {error}
            </Alert>
          )}

          {/* Watch identity */}
          <Box
            sx={{
              display:
                "grid",

              gridTemplateColumns:
              {
                xs:
                  "1fr",

                sm:
                  "1fr 1fr",

                md:
                  "repeat(3, 1fr)",
              },

              gap: 2,
            }}
          >
            <TextField
              label="מותג"
              value={brand}
              onChange={(
                event,
              ) =>
                setBrand(
                  event.target
                    .value,
                )
              }
              required
              fullWidth
              disabled={
                isSaving
              }
            />

            <TextField
              label="דגם"
              value={model}
              onChange={(
                event,
              ) =>
                setModel(
                  event.target
                    .value,
                )
              }
              required
              fullWidth
              disabled={
                isSaving
              }
            />

            <TextField
              label="שם השעון"
              value={name}
              onChange={(
                event,
              ) =>
                setName(
                  event.target
                    .value,
                )
              }
              required
              fullWidth
              disabled={
                isSaving
              }
            />
          </Box>

          {/* Description */}
          <TextField
            label="תיאור"
            value={
              description
            }
            onChange={(
              event,
            ) =>
              setDescription(
                event.target
                  .value,
              )
            }
            multiline
            minRows={3}
            fullWidth
            disabled={
              isSaving
            }
          />

          {/* Watch image gallery */}
          <Box
            sx={{
              p: {
                xs: 2,
                sm: 2.5,
              },

              border:
                "1px solid rgba(179,145,84,0.20)",

              borderRadius:
                3,

              bgcolor:
                "rgba(179,145,84,0.035)",
            }}
          >
            <Stack
              spacing={1.2}
              sx={{
                mb: 2,
              }}
            >
              <Typography
                sx={{
                  fontWeight:
                    700,
                }}
              >
                גלריית תמונות
              </Typography>

              <Typography
                variant="body2"
                color="text.secondary"
              >
                ניתן לבחור עד 10 תמונות מהמחשב או מהטלפון. התמונה הראשונה בגלריה תהיה התמונה הראשית של השעון.
              </Typography>

              <Typography
                variant="caption"
                color="text.secondary"
              >
                ניתן לבחור קובצי תמונה בגודל של עד 10MB לתמונה.
              </Typography>
            </Stack>

            <Stack
              direction={{
                xs:
                  "column",

                sm:
                  "row",
              }}
              spacing={1.2}
              sx={{
                alignItems: {
                  xs:
                    "stretch",

                  sm:
                    "center",
                },
              }}
            >
              <Button
                component="label"
                variant="outlined"
                disabled={
                  isSaving ||
                  galleryImages.length >=
                  MAX_WATCH_IMAGES
                }
              >
                בחירת תמונות

                <input
                  type="file"
                  accept="image/*"
                  multiple
                  hidden
                  onChange={(
                    event,
                  ) => {
                    handleFilesSelected(
                      event.target
                        .files,
                    );

                    /*
                     * Reset the file input so the
                     * same file can be selected again
                     * after being removed.
                     */
                    event.target.value =
                      "";
                  }}
                />
              </Button>

              <Typography
                variant="body2"
                color="text.secondary"
              >
                {galleryImages.length}/{MAX_WATCH_IMAGES} תמונות
              </Typography>
            </Stack>

            {galleryImages.length ===
              0 && (
                <Box
                  sx={{
                    mt: 2.5,

                    px: 2,
                    py: 4,

                    border:
                      "1px dashed rgba(179,145,84,0.35)",

                    borderRadius:
                      2.5,

                    textAlign:
                      "center",

                    bgcolor:
                      "#FFFFFF",
                  }}
                >
                  <Typography
                    color="text.secondary"
                    variant="body2"
                  >
                    עדיין לא נוספו תמונות לשעון
                  </Typography>
                </Box>
              )}

            {/* Gallery preview */}
            {galleryImages.length >
              0 && (
                <Box
                  sx={{
                    mt: 2.5,

                    display:
                      "grid",

                    gridTemplateColumns:
                    {
                      xs:
                        "1fr",

                      sm:
                        "repeat(2, 1fr)",

                      md:
                        "repeat(3, 1fr)",
                    },

                    gap: 1.5,
                  }}
                >
                  {galleryImages.map(
                    (
                      image,
                      index,
                    ) => (
                      <Box
                        key={
                          image.id
                        }
                        sx={{
                          overflow:
                            "hidden",

                          borderRadius:
                            2.5,

                          bgcolor:
                            "#FFFFFF",

                          border:
                            index ===
                              0
                              ? "2px solid #B39154"
                              : "1px solid #E7E4DE",

                          boxShadow:
                            index ===
                              0
                              ? "0 6px 20px rgba(179,145,84,0.12)"
                              : "none",
                        }}
                      >
                        {/* Image */}
                        <Box
                          sx={{
                            position:
                              "relative",

                            aspectRatio:
                              "1 / 1",

                            bgcolor:
                              "#FFFFFF",
                          }}
                        >
                          <Box
                            component="img"
                            src={
                              getGalleryImagePreview(
                                image,
                              )
                            }
                            alt={`תמונה ${index + 1}`}
                            sx={{
                              width:
                                "100%",

                              height:
                                "100%",

                              objectFit:
                                "contain",

                              p: 1,
                            }}
                          />

                          {index ===
                            0 && (
                              <Box
                                sx={{
                                  position:
                                    "absolute",

                                  right: 8,
                                  top: 8,

                                  px: 1,
                                  py: 0.35,

                                  borderRadius:
                                    1.2,

                                  bgcolor:
                                    "rgba(146,115,63,0.92)",

                                  color:
                                    "#FFFFFF",

                                  fontSize:
                                    "0.72rem",

                                  fontWeight:
                                    700,
                                }}
                              >
                                תמונה ראשית
                              </Box>
                            )}

                          {image.kind ===
                            "new" && (
                              <Box
                                sx={{
                                  position:
                                    "absolute",

                                  left: 8,
                                  top: 8,

                                  px: 1,
                                  py: 0.35,

                                  borderRadius:
                                    1.2,

                                  bgcolor:
                                    "rgba(255,255,255,0.94)",

                                  color:
                                    "text.secondary",

                                  fontSize:
                                    "0.68rem",

                                  fontWeight:
                                    700,

                                  border:
                                    "1px solid #E7E4DE",
                                }}
                              >
                                חדשה
                              </Box>
                            )}
                        </Box>

                        {/* Image controls */}
                        <Stack
                          spacing={0.8}
                          sx={{
                            p: 1.2,

                            borderTop:
                              "1px solid #F0EEE9",
                          }}
                        >
                          {index !==
                            0 && (
                              <Button
                                size="small"
                                variant="text"
                                disabled={
                                  isSaving
                                }
                                onClick={() =>
                                  setPrimaryImage(
                                    index,
                                  )
                                }
                              >
                                קבע כתמונה ראשית
                              </Button>
                            )}

                          <Stack
                            direction="row"
                            spacing={0.7}
                          >
                            <Button
                              size="small"
                              variant="outlined"
                              disabled={
                                isSaving ||
                                index ===
                                0
                              }
                              onClick={() =>
                                moveGalleryImage(
                                  index,
                                  -1,
                                )
                              }
                              sx={{
                                flex: 1,
                              }}
                            >
                              קודם
                            </Button>

                            <Button
                              size="small"
                              variant="outlined"
                              disabled={
                                isSaving ||
                                index ===
                                galleryImages.length -
                                1
                              }
                              onClick={() =>
                                moveGalleryImage(
                                  index,
                                  1,
                                )
                              }
                              sx={{
                                flex: 1,
                              }}
                            >
                              אחר כך
                            </Button>
                          </Stack>

                          <Button
                            size="small"
                            color="error"
                            disabled={
                              isSaving
                            }
                            onClick={() =>
                              removeGalleryImage(
                                index,
                              )
                            }
                          >
                            הסרת תמונה
                          </Button>
                        </Stack>
                      </Box>
                    ),
                  )}
                </Box>
              )}
          </Box>

          {/* Prices */}
          <Box
            sx={{
              display:
                "grid",

              gridTemplateColumns:
              {
                xs:
                  "1fr",

                md:
                  "repeat(3, 1fr)",
              },

              gap: 2,
            }}
          >
            <TextField
              label="עלות למנהל"
              type="number"
              value={
                adminCostPrice
              }
              onChange={(
                event,
              ) =>
                setAdminCostPrice(
                  event.target
                    .value,
                )
              }
              required
              fullWidth
              disabled={
                isSaving
              }
              slotProps={{
                htmlInput: {
                  min: 0,
                  step: 0.01,
                },
              }}
            />

            <TextField
              label="מחיר ברירת מחדל לספק"
              type="number"
              value={
                defaultSupplierPrice
              }
              onChange={(
                event,
              ) =>
                setDefaultSupplierPrice(
                  event.target
                    .value,
                )
              }
              required
              fullWidth
              disabled={
                isSaving
              }
              slotProps={{
                htmlInput: {
                  min: 0,
                  step: 0.01,
                },
              }}
            />

            <TextField
              label="מחיר מכירה מומלץ"
              type="number"
              value={
                recommendedSalePrice
              }
              onChange={(
                event,
              ) =>
                setRecommendedSalePrice(
                  event.target
                    .value,
                )
              }
              required
              fullWidth
              disabled={
                isSaving
              }
              slotProps={{
                htmlInput: {
                  min: 0,
                  step: 0.01,
                },
              }}
            />
          </Box>

          {/* Initial warehouse quantity */}
          {!isEdit && (
            <TextField
              label="מלאי התחלתי במחסן"
              type="number"
              value={
                initialQuantity
              }
              onChange={(
                event,
              ) =>
                setInitialQuantity(
                  event.target
                    .value,
                )
              }
              helperText="ניתן להזין 0 ולהוסיף מלאי מאוחר יותר"
              fullWidth
              disabled={
                isSaving
              }
              slotProps={{
                htmlInput: {
                  min: 0,
                  step: 1,
                },
              }}
            />
          )}
        </Stack>
      </DialogContent>

      <DialogActions
        sx={{
          px: 3,
          pb: 3,
          pt: 2,

          gap: 1,

          flexWrap:
            "wrap",
        }}
      >
        <Button
          onClick={
            onClose
          }
          disabled={
            isSaving
          }
        >
          ביטול
        </Button>

        <Button
          variant="contained"
          onClick={
            handleSave
          }
          disabled={
            isSaving
          }
        >
          {isSaving
            ? saveMessage ||
            "שומר..."
            : isEdit
              ? "שמירת שינויים"
              : "יצירת שעון"}
        </Button>
      </DialogActions>
    </Dialog>
  );
}